version: '3'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --console-address ":9001" /data
    healthcheck:
      test: timeout 1s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      start_period: 2s
      interval: 1s
      timeout: 1s
      retries: 20
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 25
  # backend:
  #   environment:
  #     S3_URL: http://minio:9000
  #     POSTGRES_HOST: postgres
  #   build:
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     minio:
  #       condition: service_healthy
  #     postgres:
  #       condition: service_healthy
