"""empty message

Revision ID: 1026dd7a78d0
Revises: 
Create Date: 2024-04-16 19:45:08.201380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1026dd7a78d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('slug', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('thread',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=True), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('board', sa.String(length=256), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['board'], ['board.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, cycle=True), nullable=False),
    sa.Column('thread', sa.Integer(), nullable=True),
    sa.Column('voice_message', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['thread'], ['thread.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thread_media_file',
    sa.Column('thread', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('s3_filename', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['thread'], ['thread.id'], ),
    sa.PrimaryKeyConstraint('s3_filename')
    )
    op.create_table('post_media_file',
    sa.Column('post', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('s3_filename', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['post'], ['post.id'], ),
    sa.PrimaryKeyConstraint('s3_filename')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_media_file')
    op.drop_table('thread_media_file')
    op.drop_table('post')
    op.drop_table('thread')
    op.drop_table('board')
    # ### end Alembic commands ###
